[general]
RemoteNickFormat="{NICK}@{PROTOCOL}"

[discord]
[discord.ario]
Token="${DISCORD_TOKEN}"
Server="${DISCORD_SERVER}"
WebhookURL="${DISCORD_WEBHOOK}"

[slack]
[slack.ario]
Token="${SLACK_ARIO_TOKEN}"
[slack.support]
Token="${SLACK_SUPPORT_TOKEN}"

[[gateway]]
name="discord.slack.random"
enable=true
inout = [
    { account="discord.ario", channel="random-slack" },
    { account="slack.ario", channel="random" },
]

[[gateway]]
name="discord.slack.links"
enable=true
inout = [
    { account="discord.ario", channel="links-slack" },
    { account="slack.ario", channel="links" },
]

[[gateway]]
name="discord.slack.news"
enable=true
inout = [
    { account="discord.ario", channel="news-slack" },
    { account="slack.ario", channel="news" },
]

[[gateway]]
name="discord.slack.smartgame"
enable=true
inout = [
    { account="discord.ario", channel="smartgame-slack" },
    { account="slack.ario", channel="smart-game" },
]

[[gateway]]
name="discord.slack.teamleads"
enable=true
inout = [
    { account="discord.ario", channel="teamleads-slack" },
    { account="slack.ario", channel="team-leads" },
]

[[gateway]]
name = "discord.slack.general"
enable=true
[[gateway.in]]
account ="slack.ario"
channel = "general"
[[gateway.out]]
account = "discord.ario"
channel="general-slack"

[[gateway]]
name = "discord.slack.problems"
enable=true
[[gateway.in]]
account ="slack.ario"
channel = "ario-problems"
[[gateway.out]]
account = "discord.ario"
channel="ario-problems-slack"
